baseballcards/baseballcards/Controllers/CardsController.cs
using baseballcards.Models;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Configuration;

namespace baseballcards.Controllers
{
    public class CardsController : Controller
    {
        private readonly ICardRepository repo;
        public CardsController(ICardRepository repo)
        {
            this.repo = repo;
        }

        // Does a search (complex)
        public async Task<IActionResult> ViewSearch(string setName, string year, string subset, string cardnumber, string firstname, string lastname, string info, string serialNumber, string autograph, string relic,int? page/*SearchModel card*/)
        {
            ViewData["CurrentSetName"] = setName;
            ViewData["CurrentYear"] = year;
            ViewData["CurrentSubset"] = subset;
            ViewData["CurrentCardnumber"] = cardnumber;
            ViewData["CurrentFirstname"] = firstname;
            ViewData["CurrentLastname"] = lastname;
            ViewData["CurrentInfo"] = info;
            ViewData["CurrentSerialNumber"] = serialNumber;
            ViewData["CurrentAutograph"] = autograph;
            ViewData["CurrentRelic"] = relic;

            var cards = repo.ComplexSearch(setName, year, subset, cardnumber, firstname, lastname, info, serialNumber, autograph, relic);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            //calculate page size
            int pageSize = 50;
            // calculate total number of pages
            int totalItems = cards.Count();
            int totalPages = (int)Math.Ceiling((decimal)totalItems / pageSize);
            // Set the current page number
            int pageNumber = (page ?? 1);
            pageNumber = Math.Max(1, Math.Min(pageNumber, totalPages));
            // Retrieve the items for the current page
            var pagedItems = cards.Skip((pageNumber - 1) * pageSize).Take(pageSize);
            // Pass the paginated items and pagination information to the view
            ViewBag.Items = pagedItems;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber; 
            return View();
        }

        //Does a search (simple)
        public async Task<IActionResult> Index(string searchString, int? page)
        {
            ViewData["CurrentFilter"] = searchString;  // ONLY displays what was typed in after search
            var cards = repo.SearchCard(searchString);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);

            //calculate page size
            int pageSize = 50;
            // calculate total number of pages
            int totalItems = cards.Count();
            int totalPages = (int)Math.Ceiling((decimal)totalItems / pageSize);
            // Set the current page number
            int pageNumber = (page ?? 1);
            pageNumber = Math.Max(1, Math.Min(pageNumber, totalPages));
            // Retrieve the items for the current page
            var pagedItems = cards.Skip((pageNumber - 1) * pageSize).Take(pageSize);
            // Pass the paginated items and pagination information to the view
            ViewBag.Items = pagedItems;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber;

            return View();
        }


        // view all cards
        public IActionResult AllCards(int? page)
        {
            var cards = repo.GetAllCards();
            // get total count
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            // calculate page size
            int pageSize = 1000;
            // calculate total number of pages
            int totalItems = cards.Count();
            int totalPages = (int)Math.Ceiling((decimal)totalItems / pageSize);
            // Set the current page number
            int pageNumber = (page ?? 1);
            pageNumber = Math.Max(1, Math.Min(pageNumber, totalPages));
            // Retrieve the items for the current page
            var pagedItems = cards.Skip((pageNumber - 1) * pageSize).Take(pageSize);
            // Pass the paginated items and pagination information to the view
            ViewBag.Items = pagedItems;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber;
            return View();
        }
        // view single card
        public IActionResult ViewCard(int id)
        {
            var card = repo.GetCard(id);
            return View(card);
        }


        //view all cards by SetName
        public IActionResult ViewSet(int id, int? page)
        {
            var setname = Convert.ToString(repo.GetCard(id).SetName);
            var cards = repo.GetSet(setname);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            // calculate page size
            int pageSize = 1000;
            // calculate total number of pages
            int totalItems = cards.Count();
            int totalPages = (int)Math.Ceiling((decimal)totalItems / pageSize);
            // Set the current page number
            int pageNumber = (page ?? 1);
            pageNumber = Math.Max(1, Math.Min(pageNumber, totalPages));
            // Retrieve the items for the current page
            var pagedItems = cards.Skip((pageNumber - 1) * pageSize).Take(pageSize);
            // Pass the paginated items and pagination information to the view
            ViewBag.Items = pagedItems;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber;
            return View();
        }
        // view all cards by Year
        public IActionResult ViewYear(int id) 
        {
            var year = Convert.ToString(repo.GetCard(id).Year);
            var cards = repo.GetYear(year);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            ViewBag.Items = cards;
            return View();
        }
        public IActionResult ViewSubset(int id)
        {
            var subset = Convert.ToString(repo.GetCard(id).Subset);
            var cards = repo.GetSubset(subset);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            ViewBag.Items = cards;
            return View();
        }
        public IActionResult ViewCardnumber(int id)
        {
            var cardnumber = Convert.ToString(repo.GetCard(id).Cardnumber);
            var cards = repo.GetCardnumber(cardnumber);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            ViewBag.Items = cards;
            return View();
        }
        public IActionResult ViewFirstname(int id)
        {
            var firstname = Convert.ToString(repo.GetCard(id).Firstname);
            var cards = repo.GetFirstname(firstname);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            ViewBag.Items = cards;
            return View();
        }
        public IActionResult ViewLastname(int id)
        {
            var lastname = Convert.ToString(repo.GetCard(id).Lastname);
            var cards = repo.GetLastname(lastname);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            ViewBag.Items = cards;
            return View();
        }
        public IActionResult ViewAutograph(int id)
        {
            var autograph = Convert.ToString(repo.GetCard(id).Autograph);
            var cards = repo.GetAutograph(autograph);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            ViewBag.Items = cards;
            return View();
        }
        public IActionResult ViewRelic(int id)
        {
            var relic = Convert.ToString(repo.GetCard(id).Relic);
            var cards = repo.GetRelic(relic);
            ViewBag.TotalCount = repo.TotalCount(cards);
            ViewBag.Unique = repo.UniqueCount(cards);
            ViewBag.Items = cards;
            return View();
        }


        // view single card to update TotalNumber 
        public IActionResult UpdateCard(int id)
        {
            Cards card = repo.GetCard(id);
            if (card == null)
            {
                return View("CardNotFound");
            }
            return View(card);
        }
        // update card to database and send to ViewCard with updated info
        public IActionResult UpdateCardToDatabase(Cards card)
        {
            repo.UpdateCard(card);
            return RedirectToAction("ViewCard", new { id = card.CardID });
        }

        // create a new card to be inserted
        public IActionResult InsertCard()
        {
            var card = new Cards();
            return View(card);
        }
        // insert card to database
        public IActionResult InsertCardToDatabase(Cards cardToInsert)
        {
            repo.InsertCard(cardToInsert);
            return RedirectToAction("Index");
        }
        // delete card from database
        public IActionResult DeleteCard(Cards card)
        {
            repo.DeleteCard(card);
            return RedirectToAction("Index");
        }
    }
}

baseballcards/baseballcards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Baseball Card Collection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/baseballcards.styles.css" asp-append-version="true"/>
    @*<link rel="stylesheet" href="~/Shared/Style.css" asp-append-version="true" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Card Collection</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cards" asp-action="Index">Quick Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cards" asp-action="ViewSearch">Full Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cards" asp-action="AllCards">All Cards</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cards" asp-action="InsertCard">Insert Card</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Robert Rogers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>